
BUILD_VERSION=2.0

spring.starks-datasource.url=jdbc:mysql://localhost:3306/starks?useSSL=false&serverTimezone=UTC
spring.starks-datasource.usename=root
spring.starks-datasource.password=Teja@554
spring.starks-datasource.driverClassName=com.mysql.cj.jdbc.Driver
